{% set name = "micromagneticmodel" %}
{% set version = "0.63.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdc46223e0709bac34cb824f2757971b1836a90c32affb6654c4047e076536cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield >=0.90.0
    - ubermagutil >=0.63.2

test:
  imports:
    - micromagneticmodel
  commands:
    - python -c "import sys; import micromagneticmodel; sys.exit(micromagneticmodel.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python-based domain-specific language for computational magnetism.
  doc_url: https://ubermag.github.io/documentation/micromagneticmodel.html
  dev_url: https://github.com/ubermag/micromagneticmodel

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
