{% set name = "micromagneticmodel" %}
{% set version = "0.7.4" %}
{% set sha256 = "b84327815a821d7cdfd130589a8f33f2d28d691b07f33949b9e0df2801a9975a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py27]
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - discretisedfield
    - joommfutil
    - pytest

test:
  imports:
    - micromagneticmodel
    - micromagneticmodel.tests
    - micromagneticmodel.drivers
    - micromagneticmodel.dynamics
    - micromagneticmodel.hamiltonian

  commands:
    - python -c "import micromagneticmodel; micromagneticmodel.test()"


about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  summary: A Python-based micromagnetic model
  license_family: BSD
  license_file: LICENSE

  description: |
    The micromagneticmodel is a representation of the physics of a
    micromagnetic problem in Python. It does not carry out any
    calculation. However, other packages derive from this abstract
    class and provide 'micromagnetic calculators'. For example the
    'oommfc' package is a micromagnetic calculator (OOMMFCalculator)
    based on the micromagneticmodel provided here, and uses OOMMF to
    carry out any actual numerical calculation.
  doc_url: http://micromagneticmodel.readthedocs.io
  dev_url: https://github.com/joommf/micromagneticmodel

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
