{% set name = "micromagneticmodel" %}
{% set version = "0.8.5" %}
{% set sha256 = "5d0455d326a73f9077731e491a3012d9fbafe79b1a2c9e0b1593053195eea6b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - discretisedfield
    - joommfutil
    - pytest

test:
  imports:
    - micromagneticmodel
    - micromagneticmodel.tests
    - micromagneticmodel.drivers
    - micromagneticmodel.dynamics
    - micromagneticmodel.hamiltonian

  commands:
    - python -c "import sys; import micromagneticmodel as m; sys.exit(m.test())"


about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  summary: A Python-based micromagnetic model
  license_family: BSD
  license_file: LICENSE

  description: |
    The micromagneticmodel is a representation of the physics of a
    micromagnetic problem in Python. It does not carry out any
    calculation. However, other packages derive from this abstract
    class and provide 'micromagnetic calculators'. For example the
    'oommfc' package is a micromagnetic calculator (OOMMFCalculator)
    based on the micromagneticmodel provided here, and uses OOMMF to
    carry out any actual numerical calculation.
  doc_url: http://micromagneticmodel.readthedocs.io
  dev_url: https://github.com/joommf/micromagneticmodel

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
    - rpep
    - davidcortesortuno
