{% set name = "micromagneticmodel" %}
{% set version = "0.8.14" %}
{% set sha256 = "46488c9e2d7485457004815359a8d5bdb02e2e0a6e8d5cebf6c75f98d2da3122" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - discretisedfield
    - pytest

test:
  imports:
    - micromagneticmodel
  commands:
    - python -c "import sys; import micromagneticmodel as mm; sys.exit(mm.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python domain-specific language for defining micromagnetic models.'
  doc_url: http://micromagneticmodel.readthedocs.io
  dev_url: https://github.com/ubermag/micromagneticmodel

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
