{% set name = "micromagneticmodel" %}
{% set version = "0.65.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3839f05f9c6de917bc0ad8dd7057865db7e3bffb72eb39bab41ae28bdb16a60

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - discretisedfield >=0.91.0
    - ubermagutil >=0.63.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - micromagneticmodel
  commands:
    - python -c "import sys; import micromagneticmodel; sys.exit(micromagneticmodel.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python-based domain-specific language for computational magnetism.
  doc_url: https://ubermag.github.io/documentation/micromagneticmodel.html
  dev_url: https://github.com/ubermag/micromagneticmodel

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
