{% set name = "micromagneticmodel" %}
{% set version = "0.8.8" %}
{% set sha256 = "4c653e7731fb21e4c92301ce7a55219174c685aa469fd9e8198f62d47aa42c58" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - discretisedfield
    - ubermagutil
    - pytest

test:
  imports:
    - micromagneticmodel
    - micromagneticmodel.tests
    - micromagneticmodel.drivers
    - micromagneticmodel.dynamics
    - micromagneticmodel.hamiltonian

  commands:
    - python -c "import sys; import micromagneticmodel as mm; sys.exit(mm.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  summary: Python domain-specific language for defining micromagnetic models.
  license_family: BSD
  license_file: LICENSE

  description: |
    `micromagneticmodel` is a Python package that provides:

    - Domain-specific language for defining micromagnetic model.

    It is available on all major operating systems (Windows, MacOS, Linux) and requires Python 3.6 or higher.
  doc_url: http://micromagneticmodel.readthedocs.io
  dev_url: https://github.com/ubermag/micromagneticmodel

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
