{% set name = "micromagneticmodel" %}
{% set version = "0.8.18" %}
{% set sha256 = "7fdbf848599773f19e36372cdfeaa4e925bc26f4da4a5a1d1baffff9b7b8b0ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - discretisedfield ==0.8.12

test:
  imports:
    - micromagneticmodel
  commands:
    - python -c "import sys; import micromagneticmodel as mm; sys.exit(mm.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python domain-specific language for defining micromagnetic models.
  doc_url: http://micromagneticmodel.readthedocs.io
  dev_url: https://github.com/ubermag/micromagneticmodel

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
