travis:
  secure:
    BINSTAR_TOKEN: gs1ec/ZseQzD0pZ2ezalN6R1VQjGTkZqOkPS3JwiA7k4vg2uKOLmc0fNzGVsncn7owP9pxcImdJW4qJWbJjdL6ShWW3SVySeheN+CqxZey8fPFUOFafZ3ra+PLqRnASs11Ukq1ywGlssBCEMyWLIuq6uYZdlPcWrm54/l/vvvOkGpWm9KESS/pyTO0kuR6Mq/Hgb+I+RpMEp1wBZjtNyL+Y/ggYeon5+9LlRCb4lCxn4gFtIm35Zk2EkclKHlcISbmBo2Lt2u2fWzpg/b1C/eT8VW4vN6KHx5s7KWxMI0yKehUGu6mQg9JFG8iTXj7D51mq7DWp8eUOYLv0I1cHOosQGqW41omB8EVoJEZl4s2BOuPBM76F/Q1CS/+TGklDqn+ONv3g8Wap57ZvcoA9OL0j4SXExy50znjVl71ngyqLXcFwye29oCbomPl34EYh7NXQ4i8vyO2zD7pMsPhsmGJsvZTI9GWuA8t08SifkBtKac3efb2bHoK2lpSlDQ6/T4jPFw7DcLM2n5CotLsF+0vrpkXtcUJ7s/q0Fwk1zarpEvKUXINbaehU7YysLEGsaj4IN+U7OqOWcjoXlP53a1gsb/OAt9kXRx/SKGFoF9MMeyrmL+JhlkJvcjBJz75VzEjs+iflBypuOVAT/8TGx2L9AgumbQryQtxxMrVSDNVo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
