travis:
  secure:
    BINSTAR_TOKEN: alALG+DKa19oPQlKle9CPlisnZ9hjNWQ2+GJ6OlHXtBa18klcWl4jqW7IQx44XDL5RPmFqGLTw5JQKynEKqPb2QLnaGnSYNZMxDPP4ofFnjnOPW/56Plxotzp4jWNEz2TYPDV6muk5Blx/+gKK1HALJShrJ3GeTSuwls8uQJvP3ZbFuTHFPIeKjKa/opz4EfpnbmgqlhwUoARWeGxL5IgwfxZGZi5RXgtnb3v3HZKqdcmrMoGv62j7+/tIj6fqaRYvRVgibg1YDEMLbkp+LssgdQdKKEt58JAwqhodcHbywS+KnRNNoLMHjhlYU11zrDy5Z6rgsSoT7Zwc8farEdioE3KwlUcT23pPQsSFCAY/9UkxVuuPvdM2k9Rgfc8AhlIdrJfHlFMk70UdoKMsXCW2Ud+ge7PYJJUSbTg75+r5HkrVMm9SN8BKNhmxkYDUuVOaoBMmoMen0fZp5H1kTJYNOsyzCZ710XJVG0P92rl3sLA92eNzGj4xhgl9BP7o+sOEScbOF8e+SyGb2qAagWoHtjWOM/4Q2cR/+c5mKlezw0Z83//TU76a9cz+8XXVlYs+lPi03yH/64sCSpvd2AWRj74J0nHuCr16SXyr91Z102ziLPr788gQedcbpklPHeeUDKJDDp+Jc8tu7wHbo13pEgBZ2WBhI2TsDIghklBjE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
